### ISSUE TITLE
ERROR Plugin load failed: hexo-asset-link

### ISSUE THREAD

**Issue by jiangxiaoqiang** [liolok/hexo-asset-link#13]
when I am using this command:

```
> hexo new draft genie-ppt
INFO  Validating config
ERROR Plugin load failed: hexo-asset-link
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/xiaoqiangjiang/source/reddwarf/frontend/reddwarftech.github.io/node_modules/.pnpm/chalk@5.3.0/node_modules/chalk/source/index.js from /Users/xiaoqiangjiang/source/reddwarf/frontend/reddwarftech.github.io/node_modules/hexo-asset-link/index.js not supported.
Instead change the require of /Users/xiaoqiangjiang/source/reddwarf/frontend/reddwarftech.github.io/node_modules/.pnpm/chalk@5.3.0/node_modules/chalk/source/index.js in /Users/xiaoqiangjiang/source/reddwarf/frontend/reddwarftech.github.io/node_modules/hexo-asset-link/index.js to a dynamic import() which is available in all CommonJS modules.
    at req (/Users/xiaoqiangjiang/source/reddwarf/frontend/reddwarftech.github.io/node_modules/.pnpm/hexo@6.0.0/node_modules/hexo/lib/hexo/index.js:285:23)
    at /Users/xiaoqiangjiang/source/reddwarf/frontend/reddwarftech.github.io/node_modules/hexo-asset-link/index.js:3:15
    at /Users/xiaoqiangjiang/source/reddwarf/frontend/reddwarftech.github.io/node_modules/.pnpm/hexo@6.0.0/node_modules/hexo/lib/hexo/index.js:298:14
From previous event:
    at Hexo.loadPlugin (/Users/xiaoqiangjiang/source/reddwarf/frontend/reddwarftech.github.io/node_modules/.pnpm/hexo@6.0.0/node_modules/hexo/lib/hexo/index.js:278:27)
    at /Users/xiaoqiangjiang/source/reddwarf/frontend/reddwarftech.github.io/node_modules/.pnpm/hexo@6.0.0/node_modules/hexo/lib/hexo/load_plugins.js:54:18
From previous event:
    at loadModules (/Users/xiaoqiangjiang/source/reddwarf/frontend/reddwarftech.github.io/node_modules/.pnpm/hexo@6.0.0/node_modules/hexo/lib/hexo/load_plugins.js:52:6)
    at module.exports (/Users/xiaoqiangjiang/source/reddwarf/frontend/reddwarftech.github.io/node_modules/.pnpm/hexo@6.0.0/node_modules/hexo/lib/hexo/load_plugins.js:11:10)
    at /Users/xiaoqiangjiang/source/reddwarf/frontend/reddwarftech.github.io/node_modules/.pnpm/hexo@6.0.0/node_modules/hexo/lib/hexo/index.js:244:36
From previous event:
    at Hexo.init (/Users/xiaoqiangjiang/source/reddwarf/frontend/reddwarftech.github.io/node_modules/.pnpm/hexo@6.0.0/node_modules/hexo/lib/hexo/index.js:239:20)
    at /Users/xiaoqiangjiang/Library/pnpm/global/5/.pnpm/hexo-cli@4.3.1/node_modules/hexo-cli/dist/hexo.js:47:21
    at processImmediate (node:internal/timers:466:21)
INFO  Created: ~/source/reddwarf/frontend/reddwarftech.github.io/source/_drafts/genie-ppt-4.md

```

what should I do to fixed this issue? I have tried:

`pnpm i hexo-asset-link
`

**Comment by liolok** [comment]
Just `hexo init` and `npm install` then `npm install --save hexo-asset-link`, `hexo new draft "test"`. Couldn't reproduce. May I see your `hexo version`?
